"use server";

import { revalidatePath } from "next/cache";
import { createAdminClient } from "@/lib/supabase/server";

export async function createGuestRequest(formData: FormData) {
  const token = formData.get("token") as string;
  const guestFirstName = formData.get("guest_first_name") as string;
  const guestLastName = formData.get("guest_last_name") as string;
  const guestEmail = (formData.get("guest_email") as string) || null;
  const guestPhone = (formData.get("guest_phone") as string) || null;
  const guestGhin = (formData.get("guest_ghin") as string) || null;

  if (!token || !guestFirstName || !guestLastName) {
    return { error: "Guest first and last name are required" };
  }

  const supabase = createAdminClient();

  // Look up the RSVP by token to get profile_id and schedule_id
  const { data: rsvp, error: rsvpError } = await supabase
    .from("rsvps")
    .select("id, profile_id, schedule_id, status")
    .eq("token", token)
    .single();

  if (rsvpError || !rsvp) {
    return { error: "Invalid RSVP token" };
  }

  // Verify the golfer is "in" (only "in" golfers can request guests)
  if (rsvp.status !== "in") {
    return {
      error: "You must be confirmed to play before requesting a guest",
    };
  }

  // Look up event's max_guests_per_week setting
  const { data: schedule } = await supabase
    .from("event_schedules")
    .select("event:events(max_guests_per_week)")
    .eq("id", rsvp.schedule_id)
    .single();

  const event = schedule?.event as unknown as { max_guests_per_week: number } | null;
  const maxGuests = event?.max_guests_per_week || 1;

  // Check how many guest requests this golfer already has for this week
  const { count: existingCount } = await supabase
    .from("guest_requests")
    .select("*", { count: "exact", head: true })
    .eq("schedule_id", rsvp.schedule_id)
    .eq("requested_by", rsvp.profile_id)
    .in("status", ["pending", "approved"]);

  if ((existingCount || 0) >= maxGuests) {
    return {
      error: `You can only request up to ${maxGuests} guest${maxGuests !== 1 ? "s" : ""} per week. You currently have ${existingCount} guest${existingCount !== 1 ? "s" : ""} requested.`,
    };
  }

  // Create the guest request (approval_token auto-generated by DB default)
  const { data: newRequest, error: insertError } = await supabase
    .from("guest_requests")
    .insert({
      schedule_id: rsvp.schedule_id,
      requested_by: rsvp.profile_id,
      guest_first_name: guestFirstName,
      guest_last_name: guestLastName,
      guest_email: guestEmail,
      guest_phone: guestPhone,
      guest_ghin_number: guestGhin,
      status: "pending",
    })
    .select("id, approval_token")
    .single();

  if (insertError || !newRequest) {
    console.error("Error creating guest request:", insertError);
    return { error: "Failed to create guest request" };
  }

  // Send immediate admin alert email for the new guest request
  try {
    await sendGuestRequestAdminAlert(
      rsvp.schedule_id,
      rsvp.profile_id,
      newRequest.id,
      newRequest.approval_token,
      guestFirstName,
      guestLastName,
      guestEmail,
      guestPhone,
      guestGhin
    );
  } catch (err) {
    // Don't fail the guest request if the admin alert fails
    console.error("Failed to send guest request admin alert:", err);
  }

  revalidatePath(`/rsvp/${token}`);
  return { success: true };
}

/**
 * Send immediate email to event admins when a guest request is submitted.
 * Includes tokenized approve/decline links.
 */
async function sendGuestRequestAdminAlert(
  scheduleId: string,
  requestedBy: string,
  guestRequestId: string,
  approvalToken: string,
  guestFirstName: string,
  guestLastName: string,
  guestEmail: string | null,
  guestPhone: string | null,
  guestGhin: string | null,
) {
  const supabase = createAdminClient();

  // Fetch requesting golfer info
  const { data: golfer } = await supabase
    .from("profiles")
    .select("first_name, last_name, email")
    .eq("id", requestedBy)
    .single();

  // Fetch schedule + event info
  const { data: schedule } = await supabase
    .from("event_schedules")
    .select("game_date, event:events(id, name)")
    .eq("id", scheduleId)
    .single();

  if (!golfer || !schedule) return;

  const event = schedule.event as unknown as { id: string; name: string };
  const formattedDate = new Date(
    schedule.game_date + "T12:00:00"
  ).toLocaleDateString("en-US", {
    weekday: "long",
    month: "long",
    day: "numeric",
  });

  const guestName = `${guestFirstName} ${guestLastName}`;
  const golferName = `${golfer.first_name} ${golfer.last_name}`;

  // Build approve/decline URLs
  const { getSiteUrl } = await import("@/lib/format");
  const baseUrl = getSiteUrl();
  const approveUrl = `${baseUrl}/api/guest-approve/${approvalToken}?action=approve`;
  const denyUrl = `${baseUrl}/api/guest-approve/${approvalToken}?action=deny`;

  // Build guest details section
  const guestDetails = [
    `<strong>${guestName}</strong>`,
    guestEmail ? `Email: ${guestEmail}` : null,
    guestPhone ? `Phone: ${guestPhone}` : null,
    guestGhin ? `GHIN: ${guestGhin}` : null,
  ].filter(Boolean);

  // Get admins for the event
  const { data: superAdmins } = await supabase
    .from("profiles")
    .select("email")
    .eq("is_super_admin", true);

  const { data: eventAdmins } = await supabase
    .from("event_admins")
    .select("role, profile:profiles(email)")
    .eq("event_id", event.id);

  const primaryAdmin = eventAdmins?.find(
    (a: Record<string, unknown>) => a.role === "primary"
  );
  const primaryAdminEmail = (
    primaryAdmin?.profile as unknown as { email: string } | null
  )?.email;

  const ccEmails = [
    ...(superAdmins || []).map((a: { email: string }) => a.email),
    ...(eventAdmins || [])
      .filter((a: Record<string, unknown>) => a.role === "secondary")
      .map(
        (a: Record<string, unknown>) =>
          (a.profile as unknown as { email: string })?.email
      ),
  ].filter((e): e is string => !!e);

  const uniqueCcEmails = [...new Set(ccEmails)].filter(
    (e) => e !== primaryAdminEmail
  );

  const toEmail = primaryAdminEmail ||
    (superAdmins && superAdmins.length > 0 ? superAdmins[0].email : null);

  if (!toEmail) return;

  const { sendEmail } = await import("@/lib/email");

  await sendEmail({
    to: toEmail,
    cc: uniqueCcEmails.length > 0 ? uniqueCcEmails : undefined,
    subject: `[${event.name}] Guest Request: ${golferName} wants to bring ${guestName}`,
    html: `
      <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 480px; margin: 0 auto; padding: 24px;">
        <div style="background: #eff6ff; border-left: 4px solid #3b82f6; padding: 16px; margin-bottom: 20px;">
          <h2 style="color: #1e40af; margin: 0 0 8px 0; font-size: 18px;">New Guest Request</h2>
          <p style="margin: 0; color: #374151;">${event.name} — ${formattedDate}</p>
        </div>

        <p style="color: #374151;"><strong>${golferName}</strong> has requested to bring a guest:</p>

        <div style="background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; margin: 16px 0;">
          ${guestDetails.map(d => `<p style="margin: 4px 0; color: #374151;">${d}</p>`).join("")}
        </div>

        <div style="margin: 24px 0; text-align: center;">
          <a href="${approveUrl}" style="display: inline-block; background: #0d9488; color: white; padding: 12px 32px; border-radius: 8px; text-decoration: none; font-weight: 600; font-size: 16px; margin-right: 12px;">Approve Guest</a>
          <a href="${denyUrl}" style="display: inline-block; background: #dc2626; color: white; padding: 12px 32px; border-radius: 8px; text-decoration: none; font-weight: 600; font-size: 16px;">Decline Guest</a>
        </div>

        <p style="color: #9ca3af; font-size: 12px; text-align: center;">Or manage this request in the <a href="${baseUrl}/admin/rsvp/${scheduleId}" style="color: #6b7280;">RSVP Management page</a>.</p>
      </div>
    `,
  });

  // Log the email
  await supabase.from("email_log").insert({
    event_id: event.id,
    schedule_id: scheduleId,
    email_type: "guest_request_pending",
    subject: `[${event.name}] Guest Request: ${golferName} wants to bring ${guestName}`,
    recipient_count: 1 + uniqueCcEmails.length,
  });
}

export async function getGuestRequests(token: string) {
  const supabase = createAdminClient();

  // Look up the RSVP by token
  const { data: rsvp } = await supabase
    .from("rsvps")
    .select("id, profile_id, schedule_id, status")
    .eq("token", token)
    .single();

  if (!rsvp) {
    return [];
  }

  // Fetch all guest requests for this golfer for this week
  const { data: guestRequests } = await supabase
    .from("guest_requests")
    .select("*")
    .eq("schedule_id", rsvp.schedule_id)
    .eq("requested_by", rsvp.profile_id)
    .order("created_at", { ascending: true });

  return guestRequests || [];
}

export async function getPastGuests(token: string) {
  const supabase = createAdminClient();

  // Look up the RSVP by token to get the golfer's profile_id
  const { data: rsvp } = await supabase
    .from("rsvps")
    .select("profile_id")
    .eq("token", token)
    .single();

  if (!rsvp) {
    return [];
  }

  // Fetch all unique past guests for this golfer
  // Group by guest email to get unique guests (most recent request per guest)
  const { data: pastGuests } = await supabase
    .from("guest_requests")
    .select("guest_first_name, guest_last_name, guest_email, guest_phone, guest_ghin_number")
    .eq("requested_by", rsvp.profile_id)
    .order("created_at", { ascending: false });

  if (!pastGuests) {
    return [];
  }

  // Deduplicate by name + email combo (keep most recent)
  const uniqueGuests = pastGuests.reduce((acc, guest) => {
    const key = `${guest.guest_first_name}|${guest.guest_last_name}|${guest.guest_email || ""}`;
    if (!acc.find((g: typeof guest) =>
      `${g.guest_first_name}|${g.guest_last_name}|${g.guest_email || ""}` === key
    )) {
      acc.push(guest);
    }
    return acc;
  }, [] as typeof pastGuests);

  return uniqueGuests;
}
