/**
 * Send a weekly invite email to a single golfer who missed the Monday send.
 *
 * Usage (from project root):
 *   npx tsx --env-file=.env.local scripts/send-invite-single.ts <email> [game-date]
 *
 * Examples:
 *   npx tsx --env-file=.env.local scripts/send-invite-single.ts tom.mccartin@marcusmillichap.com
 *   npx tsx --env-file=.env.local scripts/send-invite-single.ts tom.mccartin@marcusmillichap.com 2026-03-07
 *
 * What it does:
 *   1. Looks up the golfer's profile by email
 *   2. Finds the next upcoming game schedule for their subscribed event(s)
 *   3. Creates an RSVP row (with token) if one doesn't already exist
 *   4. Sends them the standard invite email
 */

import { createClient } from "@supabase/supabase-js";
import { Resend } from "resend";
import { generateInviteEmail } from "../src/lib/email";

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!;
const RESEND_API_KEY = process.env.RESEND_API_KEY!;
const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || "https://frccgolfgames.com";
const FROM_EMAIL = process.env.FROM_EMAIL || "happy@frccgolfgames.com";

if (!SUPABASE_URL || !SERVICE_ROLE_KEY || !RESEND_API_KEY) {
  console.error("Missing env vars. Run with: npx tsx --env-file=.env.local scripts/send-invite-single.ts <email>");
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
  auth: { autoRefreshToken: false, persistSession: false },
});
const resend = new Resend(RESEND_API_KEY);

async function main() {
  const email = process.argv[2]?.trim().toLowerCase();
  const gameDateArg = process.argv[3]?.trim(); // optional: e.g. "2026-03-07"

  if (!email) {
    console.error("Usage: npx tsx --env-file=.env.local scripts/send-invite-single.ts <email> [game-date]");
    process.exit(1);
  }

  console.log(`\nLooking up golfer: ${email}\n`);

  // 1. Find the golfer's profile
  const { data: profile, error: profileError } = await supabase
    .from("profiles")
    .select("id, first_name, last_name, email, status")
    .eq("email", email)
    .single();

  if (profileError || !profile) {
    console.error(`No profile found for ${email}`);
    process.exit(1);
  }

  if (profile.status !== "active") {
    console.error(`Golfer is not active (status: ${profile.status}). Aborting.`);
    process.exit(1);
  }

  console.log(`Found: ${profile.first_name} ${profile.last_name} (${profile.status})`);

  // 2. Find their active event subscriptions
  const { data: subscriptions } = await supabase
    .from("event_subscriptions")
    .select("event_id, event:events(id, name, default_capacity, cutoff_day, cutoff_time)")
    .eq("profile_id", profile.id)
    .eq("is_active", true);

  if (!subscriptions?.length) {
    console.error("Golfer has no active event subscriptions.");
    process.exit(1);
  }

  console.log(`Subscribed to ${subscriptions.length} event(s)\n`);

  let sent = 0;

  for (const sub of subscriptions) {
    const event = sub.event as { id: string; name: string; default_capacity: number; cutoff_day: number; cutoff_time: string };
    if (!event) continue;

    // 3. Find the schedule row
    let scheduleQuery = supabase
      .from("event_schedules")
      .select("id, game_date, invite_sent, status, capacity")
      .eq("event_id", event.id)
      .neq("status", "cancelled");

    if (gameDateArg) {
      scheduleQuery = scheduleQuery.eq("game_date", gameDateArg);
    } else {
      // Find the next upcoming game
      scheduleQuery = scheduleQuery
        .gte("game_date", new Date().toISOString().split("T")[0])
        .order("game_date", { ascending: true })
        .limit(1);
    }

    const { data: schedules } = await scheduleQuery;
    const schedule = schedules?.[0];

    if (!schedule) {
      console.log(`  [${event.name}] No upcoming schedule found — skipping.`);
      continue;
    }

    console.log(`  [${event.name}] Schedule: ${schedule.game_date} (invite_sent: ${schedule.invite_sent})`);

    // 4. Check if RSVP row already exists
    const { data: existingRsvp } = await supabase
      .from("rsvps")
      .select("id, token, status")
      .eq("schedule_id", schedule.id)
      .eq("profile_id", profile.id)
      .maybeSingle();

    let token: string;

    if (existingRsvp) {
      token = existingRsvp.token;
      console.log(`  RSVP row already exists (status: ${existingRsvp.status}) — reusing token`);
    } else {
      // Create the RSVP row (token is auto-generated by the DB)
      const { data: newRsvp, error: insertError } = await supabase
        .from("rsvps")
        .insert({
          schedule_id: schedule.id,
          profile_id: profile.id,
          status: "no_response",
        })
        .select("token")
        .single();

      if (insertError || !newRsvp) {
        console.error(`  ERROR creating RSVP row: ${insertError?.message}`);
        continue;
      }
      token = newRsvp.token;
      console.log(`  Created new RSVP row with token`);
    }

    // 5. Generate and send the invite email
    const gameDate = schedule.game_date;
    const formattedDate = new Date(gameDate + "T12:00:00").toLocaleDateString("en-US", {
      month: "long",
      day: "numeric",
    });

    const html = generateInviteEmail({
      golferName: profile.first_name,
      eventName: event.name,
      gameDate,
      rsvpToken: token,
      siteUrl: SITE_URL,
    });

    const { data: sendData, error: sendError } = await resend.emails.send({
      from: `FRCC Golf Games <${FROM_EMAIL}>`,
      to: [profile.email],
      subject: `${event.name}: ${formattedDate} — Are You In?`,
      html,
    });

    if (sendError) {
      console.error(`  ERROR sending email: ${JSON.stringify(sendError)}`);
    } else {
      console.log(`  ✓ Invite sent to ${profile.email} (Resend ID: ${sendData?.id})`);
      console.log(`  RSVP link: ${SITE_URL}/rsvp/${token}`);
      sent++;
    }
  }

  console.log(`\n========================================`);
  console.log(`  Emails sent: ${sent} / ${subscriptions.length}`);
  console.log(`========================================\n`);
}

main().catch((err) => {
  console.error("Unexpected error:", err);
  process.exit(1);
});
